name: protobuf
version: 1.1.4
description: >-
  Runtime library for protocol buffers support.
  Use https://pub.dev/packages/protoc_plugin to generate dart code for your '.proto' files.
homepage: https://github.com/dart-lang/protobuf

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  fixnum: '>=0.10.9 <2.0.0'

dev_dependencies:
  test: '>=1.2.0'
  benchmark_harness: any
  js: any
  matcher: any
  pedantic: ^1.9.2
